
server:
  port: 80

spring:
  application:
    name: cloud-consumer-openfeign-hystrix-order

eureka:
  client:
    register-with-eureka: true     #true表示向注册中心注册自己。
    fetchregistry: true     #true 表示去检索服务
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/

ribbon:
  #设置 OpenFeign 中自带的ribbon建立连接时间为 5S，默认为 1S 在处理复杂业务逻辑的时候，1S不够用 就等待 5S
  ReadTimeout: 5000
  #设置建立连接以后从服务器读取到可用资源的所用时间
  ConnectTimeout: 5000


  #设置OpenFeign的日志打印级别
logging:
  level:
    com.llx.springcloud.service.OrderService: debug


feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。
