
server:
  port: 80

spring:
  application:
    name: cloud-eureka-client-order

eureka:
  client:
    register-with-eureka: true     #true表示向注册中心注册自己。
    fetchregistry: true     #true 表示去检索服务
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/



